.TH tpl 1 "2014" "" "User Manual"
.SH NAME
tpl \- a simple template-based file creator
.SH SYNOPSIS
tpl \fITEMPLATE_NAME\fR \fILANGUAGE_NAME\fR
.RB [ -a
.IR AUTHOR ]
.RB [ -p
.IR PROJECT ]
.SH DESCRIPTION
Write down on stdout a template named \fITEMPLATE_NAME\fR filled with the
matching context values and put in the form of a comment according to the
specified \fILANGUAGE_NAME\fR programming language.
.SH OPTIONS
.TP
.BI \-a \-\-author " AUTHOR"
specify another author instead of the default one.
.TP
.BI \-p \-\-project " PROJECT"
specify another project name instead of the default one.
.SH NOTES
The base program is handling only a few number of templates and languages which
are listed below. Some languages may have the same comment format and therefore
can be switched together because the result will stay the same (e.g, Python and
Bash).

Availaible templates: gpl, agpl

Availaible languages: c, cpp, python, ocaml, bash, erlang
.SS User configuration file

In order to avoid to use the author option each time tpl is called, this
software provides support of a minimalistic JSON configuration file named
\fi~/.tplrc\fR.

Here is an example of \fi~/.tplrc\fR file:

    {"author": "Romain Porte"}

Feel free to create one too and adapt it to your own needs.

.SH AUTHOR
Romain Porte <microjoe@mailoo.org>
.SH COPYRIGHT
Copyright (C) 2014 Romain Porte.
.UR http://gnu.org/licenses/gpl.html
License GPLv3+: GNU General Public License version 3 or later
.UE .
.br
This is free software: you are free to change and redistribute it.  There is NO
WARRANTY, to the extent permitted by law.
